// ============================================================
// MINI-QUIZ DATA
// ============================================================

const TOPIC_QUIZZES = {
  variables_and_types: [
    { q: 'What keyword declares a block-scoped variable that can be reassigned?', opts: ['var', 'let', 'const', 'static'], answer: 1, hint: 'Think about which keyword is NOT function-scoped and allows re-assignment.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let', explanation: 'let is block-scoped (unlike var which is function-scoped) and allows reassignment (unlike const).' },
    { q: 'What does typeof null return?', opts: ['"null"', '"undefined"', '"object"', '"boolean"'], answer: 2, hint: 'This is a famous historical bug in JavaScript.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof', explanation: 'This is a well-known JS bug from the first implementation. typeof null returns "object" due to how type tags were stored internally.' },
    { q: 'Which comparison operator checks both value and type?', opts: ['==', '===', '!=', '>='], answer: 1, hint: 'One of these uses strict equality without type coercion.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality', explanation: '=== (strict equality) compares without type coercion, so 1 === "1" is false, while 1 == "1" is true.' },
    { q: 'What does this code print?', code: 'let a = "5";\nlet b = 2;\nconsole.log(a + b);\nconsole.log(a - b);', opts: ['"52" and 3', '7 and 3', '"52" and "52"', 'NaN and NaN'], answer: 0, explanation: 'The + operator concatenates when one operand is a string: "5"+2 = "52". But - always converts to numbers: "5"-2 = 3.' },
    { q: 'What does this code print?', code: 'console.log(typeof undefined);\nconsole.log(typeof undeclaredVar);', opts: ['Error thrown', '"undefined" and "undefined"', '"undefined" and ReferenceError', '"undefined" and "null"'], answer: 1, explanation: 'typeof is special — it returns "undefined" for both undefined values AND undeclared variables without throwing.' }
  ],
  operator_aritmetical: [
    { q: 'What does 10 % 3 return?', opts: ['3', '1', '0', '3.33'], answer: 1, explanation: 'The modulo operator (%) returns the remainder of division. 10 / 3 = 3 remainder 1.' },
    { q: 'What is the result of 2 ** 3?', opts: ['6', '8', '9', '5'], answer: 1, explanation: 'The exponentiation operator (**) raises the left operand to the power of the right. 2³ = 8.' },
    { q: 'What does +"42" evaluate to?', opts: ['NaN', '"42"', '42', 'undefined'], answer: 2, explanation: 'The unary + operator converts its operand to a number. +"42" becomes the number 42.' },
    { q: 'What is typeof (1 / 0)?', opts: ['"undefined"', '"NaN"', '"number"', '"Infinity"'], answer: 2, explanation: '1 / 0 evaluates to Infinity, and typeof Infinity is "number". Infinity is a numeric value in JS.' }
  ],
  operator_assignative: [
    { q: 'What does x += 5 do?', opts: ['Compares x to 5', 'Assigns 5 to x', 'Adds 5 to x and reassigns', 'Returns x + 5'], answer: 2, explanation: 'x += 5 is shorthand for x = x + 5. It adds 5 to x and stores the result back in x.' },
    { q: 'What is the result of let x = 10; x ??= 20?', opts: ['20', '10', 'null', 'undefined'], answer: 1, explanation: '??= only assigns if the left side is null or undefined. Since x is 10 (not nullish), it stays 10.' },
    { q: 'What does x &&= y do?', opts: ['Always assigns y to x', 'Assigns y to x only if x is truthy', 'Assigns y to x only if x is falsy', 'Logical AND of x and y'], answer: 1, explanation: '&&= is the logical AND assignment. It only assigns the right side if the left side is truthy.' },
    { q: 'What does let a = 8; a >>= 2 produce?', opts: ['4', '2', '32', '16'], answer: 1, explanation: '>>= is the right shift assignment. 8 >> 2 shifts binary 1000 right by 2 positions = 10 (decimal 2).' }
  ],
  operator_conditional: [
    { q: 'What does the ternary operator ?: return?', opts: ['Always true', 'One of two values based on a condition', 'A boolean', 'undefined'], answer: 1, explanation: 'The ternary operator evaluates condition ? valueIfTrue : valueIfFalse, returning one of two expressions.' },
    { q: 'What does x ?? y return?', opts: ['x if x is falsy', 'y if x is null or undefined', 'y always', 'x always'], answer: 1, explanation: 'The nullish coalescing operator (??) returns y only when x is null or undefined, not for other falsy values like 0 or "".' },
    { q: 'What does 0 ?? "default" return?', opts: ['"default"', '0', 'null', 'false'], answer: 1, explanation: '?? only triggers on null/undefined. Since 0 is not nullish (just falsy), it returns 0.' },
    { q: 'What does a?.b?.c do if a is null?', opts: ['Throws TypeError', 'Returns undefined', 'Returns null', 'Returns ""'], answer: 1, explanation: 'Optional chaining (?.) short-circuits and returns undefined if a is null or undefined, instead of throwing.' }
  ],
  operator_logical: [
    { q: 'What does false || "hello" return?', opts: ['false', 'true', '"hello"', 'undefined'], answer: 2, explanation: 'The OR operator returns the first truthy value. false is falsy, so it returns "hello".' },
    { q: 'What does true && 0 return?', opts: ['true', 'false', '0', '1'], answer: 2, explanation: 'The AND operator returns the first falsy value or the last value. true is truthy, so it evaluates and returns 0.' },
    { q: 'What does !!"" evaluate to?', opts: ['true', 'false', '""', 'undefined'], answer: 1, explanation: '"" is falsy, so !"" is true, and !!"" is false. Double negation converts to boolean.' },
    { q: 'What does null || 0 || "" || "hi" return?', opts: ['null', '0', '""', '"hi"'], answer: 3, explanation: 'OR returns the first truthy value. null, 0, and "" are all falsy, so it returns "hi".' },
    { q: 'What does this code print?', code: 'let a = 0;\nlet b = "";\nlet c = "JS";\nconsole.log(a || b || c);', opts: ['0', '""', '"JS"', 'false'], answer: 2, explanation: 'OR (||) skips falsy values (0, ""), returning the first truthy one: "JS".' }
  ],
  control_flow: [
    { q: 'Which loop always executes at least once?', opts: ['for', 'while', 'do...while', 'for...of'], answer: 2, explanation: 'do...while checks the condition after executing the body, so it always runs at least once.' },
    { q: 'What does "break" do inside a loop?', opts: ['Skips iteration', 'Exits loop', 'Returns value', 'Pauses execution'], answer: 1, explanation: 'break immediately terminates the innermost enclosing loop. Use "continue" to skip to the next iteration.' },
    { q: 'for...of iterates over:', opts: ['Object keys', 'Iterable values', 'Array indices', 'Prototype chain'], answer: 1, explanation: 'for...of iterates over iterable values (arrays, strings, Maps, Sets). Use for...in for object keys.' },
    { q: 'What happens if no case matches in a switch without default?', opts: ['Error', 'Returns undefined', 'Nothing executes', 'First case runs'], answer: 2, explanation: 'Without a matching case or default clause, the switch statement simply does nothing and execution continues after it.' },
    { q: 'What does this code print?', code: 'for (let i = 0; i < 5; i++) {\n  if (i === 3) continue;\n  if (i === 4) break;\n  console.log(i);\n}', opts: ['0, 1, 2, 3, 4', '0, 1, 2', '0, 1, 2, 4', '0, 1, 2, 3'], answer: 1, explanation: 'Prints 0, 1, 2. At i=3 continue skips the log. At i=4 break exits the loop entirely. So only 0, 1, 2 are printed.' }
  ],
  closures_and_scope: [
    { q: 'What is a closure?', opts: ['A function inside a class', 'A function that remembers its outer scope', 'An arrow function', 'A recursive function'], answer: 1, hint: 'Think about what happens when an inner function accesses variables from its parent.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures', explanation: 'A closure is created when an inner function retains access to variables from its outer (enclosing) function even after the outer function has returned.' },
    { q: 'Variables declared with var are scoped to the nearest...', opts: ['Block', 'Function', 'Module', 'Loop'], answer: 1, hint: 'var ignores curly braces from if/for — it only respects one type of boundary.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var', explanation: 'var is function-scoped, meaning it ignores block boundaries like if/for. Use let/const for block scoping.' },
    { q: 'What does this code print?', code: 'for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}\n// After all timeouts fire:', opts: ['0, 1, 2', '3, 3, 3', '0, 0, 0', 'undefined x3'], answer: 1, explanation: 'Classic closure trap! var is function-scoped, so all 3 callbacks share the same i. By the time they run, the loop has finished and i = 3. Use let to fix.' },
    { q: 'What does this code print?', code: 'function outer() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nconst fn = outer();\nconsole.log(fn(), fn(), fn());', opts: ['0 0 0', '1 1 1', '1 2 3', 'Error'], answer: 2, explanation: 'The inner function closes over count. Each call increments the same count variable: 1, 2, 3.' }
  ],
  functions: [
    { q: 'Arrow functions do NOT have their own:', opts: ['parameters', 'return value', 'this binding', 'variables'], answer: 2, hint: 'Arrow functions inherit something from their surrounding code.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions', explanation: 'Arrow functions inherit "this" from their enclosing lexical scope. They also lack arguments object and cannot be used as constructors.' },
    { q: 'What is an IIFE?', opts: ['An async function', 'A function that invokes itself immediately', 'A generator', 'A method'], answer: 1, hint: 'The acronym stands for Immediately Invoked Function Expression.', mdn: 'https://developer.mozilla.org/en-US/docs/Glossary/IIFE', explanation: 'IIFE (Immediately Invoked Function Expression) is a function defined and called in one step: (function(){})().' },
    { q: 'What are default parameters?', opts: ['Parameters that are always required', 'Values used when argument is undefined', 'Global variables', 'Rest parameters'], answer: 1, explanation: 'Default parameters provide fallback values when arguments are not passed or are undefined: function f(x = 10) {}.' },
    { q: 'What does arguments refer to inside a regular function?', opts: ['An array of parameters', 'An array-like object of passed arguments', 'The function name', 'undefined'], answer: 1, explanation: 'arguments is an array-like object containing all passed arguments. Arrow functions do not have their own arguments.' },
    { q: 'What does this code print?', code: 'console.log(greet());\nfunction greet() {\n  return "Hello!";\n}', opts: ['Error: greet is not defined', '"Hello!"', 'undefined', 'null'], answer: 1, explanation: 'Function declarations are hoisted — the entire function is available before its position in the code. Function expressions are NOT hoisted.' }
  ],
  strings: [
    { q: 'What does "hello".slice(1, 3) return?', opts: ['"hel"', '"el"', '"ell"', '"llo"'], answer: 1, explanation: 'slice(1, 3) extracts characters from index 1 up to (not including) index 3: "e" and "l" = "el".' },
    { q: 'Which method checks if a string starts with a value?', opts: ['includes()', 'startsWith()', 'indexOf()', 'match()'], answer: 1, explanation: 'startsWith() returns true if the string begins with the specified characters. endsWith() checks the end.' },
    { q: 'What does "abc".repeat(3) return?', opts: ['"abc3"', '"abcabcabc"', '["abc","abc","abc"]', '"aaa"'], answer: 1, explanation: 'repeat(n) returns a new string with n copies of the original string concatenated together.' },
    { q: 'Template literals use which character?', opts: ['Single quotes', 'Double quotes', 'Backticks', 'Parentheses'], answer: 2, explanation: 'Template literals use backticks (`) and support string interpolation with ${expression} and multi-line strings.' },
    { q: 'What does this code print?', code: 'const str = "JavaScript";\nconsole.log(str[0]);\nconsole.log(str.at(-1));\nconsole.log(str.length);', opts: ['"J", "t", 10', '"J", "t", 9', '"J", undefined, 10', '"j", "t", 10'], answer: 0, explanation: 'str[0] = "J" (first char). str.at(-1) = "t" (last char via negative index). "JavaScript" has 10 characters.' }
  ],
  regex: [
    { q: 'What flag makes a regex case-insensitive?', opts: ['g', 'i', 'm', 's'], answer: 1, explanation: 'The "i" flag enables case-insensitive matching. "g" is global, "m" is multiline, "s" makes . match newlines.' },
    { q: 'What does \\d match?', opts: ['Any digit', 'Any letter', 'Any whitespace', 'Any character'], answer: 0, explanation: '\\d matches any digit (0-9). \\w matches word chars, \\s matches whitespace, . matches any character except newline.' },
    { q: 'What does /^hello$/ match?', opts: ['Any string containing hello', 'Only the exact string "hello"', 'Strings starting with hello', 'Strings ending with hello'], answer: 1, explanation: '^ asserts start of string, $ asserts end. Together they ensure the entire string is exactly "hello".' },
    { q: 'What does str.match(/a/g) return if str = "banana"?', opts: ['["a"]', '["a","a","a"]', '"a"', '3'], answer: 1, explanation: 'With the global flag (g), match() returns an array of ALL matches. "banana" has 3 "a" characters.' }
  ],
  data_collections_arrays: [
    { q: 'Which method returns a new array without modifying the original?', opts: ['push()', 'splice()', 'map()', 'sort()'], answer: 2, hint: 'Three of these mutate the original array. One creates a brand new one.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map', explanation: 'map() creates a new array with the results of calling a function on every element. push/splice/sort mutate the original.' },
    { q: 'What does [1,2,3].reduce((a,b) => a+b, 0) return?', opts: ['[1,2,3]', '6', '0', '3'], answer: 1, explanation: 'reduce() accumulates values: 0+1=1, 1+2=3, 3+3=6. The second argument (0) is the initial accumulator value.' },
    { q: 'What does [1,2,3].find(x => x > 1) return?', opts: ['[2,3]', '2', 'true', '1'], answer: 1, explanation: 'find() returns the FIRST element that satisfies the condition. Use filter() to get all matching elements.' },
    { q: 'What does Array.isArray("hello") return?', opts: ['true', 'false', 'undefined', 'Error'], answer: 1, explanation: 'Array.isArray() checks if the value is an array. Strings are not arrays, so it returns false.' },
    { q: 'What does this code print?', code: 'const arr = [1, 2, 3, 4, 5];\nconst result = arr\n  .filter(x => x % 2 !== 0)\n  .map(x => x * 10);\nconsole.log(result);', opts: ['[10, 30, 50]', '[20, 40]', '[10, 20, 30, 40, 50]', '[1, 3, 5]'], answer: 0, explanation: 'filter keeps odd numbers [1,3,5], then map multiplies each by 10: [10, 30, 50]. Chaining is a common array pattern.' }
  ],
  data_collections_objects: [
    { q: 'Which method returns an array of an object\'s keys?', opts: ['Object.values()', 'Object.keys()', 'Object.entries()', 'Object.assign()'], answer: 1, explanation: 'Object.keys() returns an array of own enumerable property names. values() returns values, entries() returns [key, value] pairs.' },
    { q: 'What does Object.freeze() do?', opts: ['Deletes properties', 'Prevents adding/modifying properties', 'Deep clones', 'Seals the object'], answer: 1, explanation: 'Object.freeze() makes an object immutable — no adding, removing, or modifying properties. It is shallow (nested objects are not frozen).' },
    { q: 'What does {...a, ...b} do?', opts: ['Deep merges a and b', 'Shallow merges, b overwrites a', 'Creates an array', 'Clones only a'], answer: 1, explanation: 'The spread operator creates a shallow copy. Properties from b overwrite same-named properties from a.' },
    { q: 'What does Object.entries({x:1, y:2}) return?', opts: ['["x","y"]', '[[\"x\",1],[\"y\",2]]', '[1,2]', '{x:1,y:2}'], answer: 1, explanation: 'Object.entries() returns an array of [key, value] pairs: [["x",1],["y",2]].' }
  ],
  promises_and_async: [
    { q: 'What does async/await simplify?', opts: ['Loops', 'Promise chains', 'DOM manipulation', 'RegEx'], answer: 1, hint: 'async/await is syntactic sugar for a specific asynchronous pattern.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function', explanation: 'async/await is syntactic sugar over Promises, letting you write asynchronous code that reads like synchronous code.' },
    { q: 'Promise.all() resolves when:', opts: ['Any promise resolves', 'All promises resolve', 'First promise settles', 'All promises reject'], answer: 1, hint: 'Think about the name: all. What does it wait for?', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all', explanation: 'Promise.all() waits for ALL promises to resolve. If any rejects, the whole thing rejects. Use Promise.allSettled() to wait for all regardless.' },
    { q: 'What does this code print?', code: 'async function getData() {\n  return 42;\n}\nconsole.log(typeof getData());', opts: ['"number"', '"object"', '"undefined"', '"function"'], answer: 1, explanation: 'async functions ALWAYS return a Promise, even if you return a plain value. typeof Promise is "object".' },
    { q: 'In what order does this print?', code: 'console.log("A");\nPromise.resolve().then(() => console.log("B"));\nconsole.log("C");', opts: ['A, B, C', 'A, C, B', 'B, A, C', 'C, A, B'], answer: 1, explanation: 'Synchronous code runs first (A, C), then the microtask queue (Promise.then) runs B.' }
  ],
  error_handling: [
    { q: 'Which block always executes whether error occurs or not?', opts: ['try', 'catch', 'finally', 'throw'], answer: 2, hint: 'One of these blocks is designed for cleanup that must always run.', mdn: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch', explanation: 'finally always runs after try/catch, whether an error occurred or not — useful for cleanup tasks.' },
    { q: 'How do you create a custom error?', opts: ['new Error()', 'throw "error"', 'class MyError extends Error', 'All of the above'], answer: 3, explanation: 'All three work: new Error() creates a standard error, throw can throw anything, and extending Error creates custom types.' },
    { q: 'What property gives the error description?', opts: ['.text', '.message', '.description', '.info'], answer: 1, explanation: 'Error objects have .message (description), .name (error type), and .stack (call trace).' },
    { q: 'What does throw do?', opts: ['Catches an error', 'Creates an error silently', 'Stops execution and signals an error', 'Logs to console'], answer: 2, explanation: 'throw immediately stops the current execution and transfers control to the nearest catch block.' },
    { q: 'What does this code print?', code: 'try {\n  throw new Error("oops");\n  console.log("A");\n} catch (e) {\n  console.log("B");\n} finally {\n  console.log("C");\n}', opts: ['A, B, C', 'B, C', 'A, C', 'C only'], answer: 1, explanation: 'throw jumps to catch (skipping "A"), printing "B". finally always runs, printing "C". Result: B, C.' }
  ],
  fetch_api: [
    { q: 'fetch() returns a:', opts: ['String', 'JSON object', 'Promise', 'Response'], answer: 2, hint: 'fetch is asynchronous — what type of object represents async operations?', mdn: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API', explanation: 'fetch() is Promise-based. It resolves to a Response object; you then call .json() or .text() to parse the body.' },
    { q: 'How do you cancel a fetch request?', opts: ['fetch.cancel()', 'AbortController', 'clearTimeout()', 'Promise.reject()'], answer: 1, explanation: 'AbortController creates a signal that can be passed to fetch. Calling controller.abort() cancels the request.' },
    { q: 'Does fetch reject on HTTP 404/500 errors?', opts: ['Yes always', 'No, only on network failure', 'Only on 500', 'Depends on browser'], answer: 1, explanation: 'fetch() only rejects on network failures. For HTTP errors, check response.ok or response.status manually.' },
    { q: 'How do you send a POST request with fetch?', opts: ['fetch(url, "POST")', 'fetch(url, {method:"POST"})', 'fetch.post(url)', 'fetch(url).post()'], answer: 1, explanation: 'Pass an options object as the second argument with method, headers, and body properties.' }
  ],
  dom_manipulation: [
    { q: 'Which method selects the first matching element?', opts: ['getElementById()', 'querySelector()', 'querySelectorAll()', 'getElementsByClassName()'], answer: 1, explanation: 'querySelector() returns the first element matching a CSS selector. getElementById() matches by ID only.' },
    { q: 'What does element.remove() do?', opts: ['Hides element', 'Removes from DOM', 'Clears innerHTML', 'Removes attributes'], answer: 1, explanation: 'remove() detaches the element from the DOM entirely. The JS reference still exists but the element is no longer visible.' },
    { q: 'What is a DocumentFragment?', opts: ['A string of HTML', 'A lightweight container for DOM nodes', 'A CSS selector', 'An event type'], answer: 1, explanation: 'DocumentFragment is a minimal DOM node that has no parent. Used to batch DOM operations before inserting, improving performance.' },
    { q: 'dataset.myValue accesses which HTML attribute?', opts: ['my-value', 'data-my-value', 'myValue', 'value'], answer: 1, explanation: 'The dataset property provides access to data-* attributes. data-my-value becomes element.dataset.myValue (camelCase).' }
  ],
  dom_events: [
    { q: 'Which method attaches an event handler?', opts: ['onclick()', 'addEventListener()', 'attachEvent()', 'bindEvent()'], answer: 1, explanation: 'addEventListener() is the modern standard. It supports multiple handlers per event and options like capture/once.' },
    { q: 'Event delegation uses which propagation phase?', opts: ['Capture', 'Bubble', 'Target', 'None'], answer: 1, explanation: 'Event delegation attaches a single listener to a parent, leveraging event bubbling to handle events from child elements.' },
    { q: 'e.stopPropagation() prevents:', opts: ['Default action', 'Event from reaching other listeners on the same element', 'Event from reaching parent elements', 'All of the above'], answer: 2, explanation: 'stopPropagation() stops the event from bubbling to parent elements. Use preventDefault() to stop the default action.' },
    { q: 'What does {once: true} do in addEventListener?', opts: ['Fires handler once then auto-removes', 'Ensures only one handler exists', 'Delays execution', 'Prevents bubbling'], answer: 0, explanation: 'The once option automatically removes the listener after the first invocation, equivalent to manually calling removeEventListener.' }
  ],
  event_loop: [
    { q: 'Microtasks (Promise.then) execute before:', opts: ['Synchronous code', 'Macrotasks (setTimeout)', 'The call stack', 'Nothing'], answer: 1, explanation: 'After the call stack empties, all microtasks (Promises) run before the next macrotask (setTimeout, setInterval).' },
    { q: 'setTimeout(fn, 0) runs:', opts: ['Immediately', 'After current call stack clears', 'Never', 'Before promises'], answer: 1, explanation: 'setTimeout(fn, 0) queues a macrotask. It runs after the stack clears AND after all pending microtasks.' },
    { q: 'queueMicrotask() schedules a:', opts: ['Macrotask', 'Microtask', 'Animation frame', 'Web Worker'], answer: 1, explanation: 'queueMicrotask() adds a callback to the microtask queue, similar to Promise.resolve().then(fn).' },
    { q: 'requestAnimationFrame runs before:', opts: ['Microtasks', 'The next repaint', 'setTimeout(fn,0)', 'Synchronous code'], answer: 1, explanation: 'requestAnimationFrame callbacks run right before the browser\'s next repaint cycle, typically at 60fps.' },
    { q: 'What order does this print?', code: 'console.log("1");\nsetTimeout(() => console.log("2"), 0);\nPromise.resolve().then(() => console.log("3"));\nconsole.log("4");', opts: ['1, 2, 3, 4', '1, 4, 3, 2', '1, 4, 2, 3', '1, 3, 4, 2'], answer: 1, explanation: 'Sync first: 1, 4. Then microtask (Promise): 3. Then macrotask (setTimeout): 2. Order: 1, 4, 3, 2.' }
  ],
  classes_and_oop: [
    { q: 'What keyword creates a subclass?', opts: ['implements', 'extends', 'inherits', 'uses'], answer: 1, explanation: 'extends creates a class that inherits from another. The child class gets all parent methods and can override them.' },
    { q: 'Private fields in JS classes start with:', opts: ['_', '#', '@', '$'], answer: 1, explanation: '#privateField is truly private in JS classes — not accessible outside the class body. _ is only a naming convention.' },
    { q: 'super() must be called:', opts: ['In any method', 'Before using "this" in a subclass constructor', 'After return', 'Only in static methods'], answer: 1, explanation: 'In a subclass constructor, super() must be called before accessing "this", as it initializes the parent class.' },
    { q: 'Static methods belong to:', opts: ['Each instance', 'The class itself', 'The prototype', 'The global scope'], answer: 1, explanation: 'Static methods are called on the class (e.g., Array.isArray()), not on instances. Defined with the static keyword.' },
    { q: 'What does this code print?', code: 'class Animal {\n  speak() { return "..."; }\n}\nclass Dog extends Animal {\n  speak() { return "Woof!"; }\n}\nconst d = new Dog();\nconsole.log(d.speak());\nconsole.log(d instanceof Animal);', opts: ['"Woof!" and true', '"..." and true', '"Woof!" and false', 'Error'], answer: 0, explanation: 'Dog overrides speak() so d.speak() = "Woof!". d is an instance of Dog AND Animal (via prototype chain), so instanceof returns true.' }
  ],
  iterators_generators: [
    { q: 'A generator function is declared with:', opts: ['function*', 'async function', 'gen function', 'yield function'], answer: 0, explanation: 'The asterisk after function (function*) marks it as a generator that can yield multiple values.' },
    { q: 'What does yield do?', opts: ['Returns and exits', 'Pauses and produces a value', 'Throws an error', 'Loops'], answer: 1, explanation: 'yield pauses the generator and sends a value out. Calling next() resumes execution from where it paused.' },
    { q: 'What method advances a generator?', opts: ['.resume()', '.next()', '.continue()', '.step()'], answer: 1, explanation: 'Calling gen.next() resumes the generator until the next yield, returning {value, done}.' },
    { q: 'An object is iterable if it has:', opts: ['a .length property', 'a Symbol.iterator method', 'a .forEach method', 'a .next method'], answer: 1, explanation: 'The iterable protocol requires a [Symbol.iterator]() method that returns an iterator with a .next() method.' },
    { q: 'What does this code print?', code: 'function* counter() {\n  yield 1;\n  yield 2;\n  yield 3;\n}\nconst gen = counter();\nconsole.log(gen.next().value);\nconsole.log(gen.next().value);\nconsole.log(gen.next().done);', opts: ['1, 2, true', '1, 2, false', '1, 2, 3', '1, 2, undefined'], answer: 1, explanation: 'First next() yields 1, second yields 2. Third next() yields 3 (not done yet — done is false). It would be true on the FOURTH call.' }
  ],
  proxy_and_reflect: [
    { q: 'A Proxy wraps an object to intercept:', opts: ['Events', 'Operations like get/set', 'Network requests', 'CSS styles'], answer: 1, explanation: 'Proxy intercepts fundamental operations (get, set, delete, etc.) through handler trap functions.' },
    { q: 'Reflect.ownKeys() returns:', opts: ['Only string keys', 'Only symbol keys', 'All own keys including symbols', 'Inherited keys'], answer: 2, explanation: 'Reflect.ownKeys() returns all own property keys — strings AND symbols, unlike Object.keys() which skips symbols.' },
    { q: 'What is a Proxy "trap"?', opts: ['An error handler', 'A handler method that intercepts an operation', 'A debugging tool', 'A loop prevention'], answer: 1, explanation: 'Traps are functions in the handler object (get, set, has, etc.) that intercept corresponding operations on the target.' },
    { q: 'Proxy can make an object:', opts: ['Faster', 'Reactive/observable', 'Immutable only', 'Async'], answer: 1, explanation: 'By intercepting set/get operations, Proxies enable reactive patterns where changes automatically trigger updates.' }
  ],
  memory_and_performance: [
    { q: 'What helps prevent excessive function calls on scroll?', opts: ['Memoize', 'Debounce/Throttle', 'WeakRef', 'Proxy'], answer: 1, explanation: 'Debounce delays until quiet period; throttle limits to once per interval. Both reduce excessive event handler calls.' },
    { q: 'WeakMap keys are:', opts: ['Strings only', 'Numbers only', 'Objects (weakly held)', 'Any value'], answer: 2, explanation: 'WeakMap keys must be objects and are weakly referenced — if no other reference exists, they can be garbage collected.' },
    { q: 'What causes a memory leak?', opts: ['Using const', 'Forgotten references preventing GC', 'Using strict mode', 'Small arrays'], answer: 1, explanation: 'Memory leaks occur when objects that are no longer needed still have references (e.g., event listeners, closures, detached DOM).' },
    { q: 'requestIdleCallback runs when:', opts: ['Immediately', 'During browser idle time', 'Before every repaint', 'Every second'], answer: 1, explanation: 'requestIdleCallback schedules low-priority work to run when the browser has free time between frames.' }
  ],
  modules: [
    { q: 'Which keyword imports a module in ESM?', opts: ['require()', 'import', 'include', 'load'], answer: 1, explanation: 'ESM uses import/export syntax. require() is CommonJS (Node.js). ESM is the official JS module standard.' },
    { q: 'A file can have how many default exports?', opts: ['Unlimited', 'One', 'Two', 'Zero'], answer: 1, explanation: 'Each module can have at most one default export but unlimited named exports.' },
    { q: 'import() (dynamic) returns:', opts: ['The module directly', 'A Promise', 'undefined', 'A string'], answer: 1, explanation: 'Dynamic import() returns a Promise that resolves to the module, enabling lazy loading and code splitting.' },
    { q: 'Named exports are imported with:', opts: ['import x from', 'import {x} from', 'import * from', 'require(x)'], answer: 1, explanation: 'Named exports use destructuring syntax: import {x, y} from "module". Default exports use import x from "module".' }
  ],
  web_storage: [
    { q: 'localStorage data persists until:', opts: ['Tab closes', 'Browser closes', 'Manually cleared', 'Page refreshes'], answer: 2, explanation: 'localStorage has no expiration — data persists until explicitly removed via removeItem() or clear().' },
    { q: 'sessionStorage data persists until:', opts: ['Tab/window closes', 'Browser closes', 'Manually cleared', 'Forever'], answer: 0, explanation: 'sessionStorage is scoped to the tab/window. Data is cleared when the tab is closed.' },
    { q: 'localStorage stores data as:', opts: ['JSON', 'Binary', 'Strings only', 'Any JS type'], answer: 2, explanation: 'localStorage only stores strings. Use JSON.stringify() to store objects and JSON.parse() to retrieve them.' },
    { q: 'The "storage" event fires:', opts: ['On the same tab', 'On other tabs of same origin', 'On all browsers', 'Never automatically'], answer: 1, explanation: 'The storage event fires on OTHER tabs/windows of the same origin when localStorage changes, enabling cross-tab sync.' }
  ],
  web_apis: [
    { q: 'Which API accesses the clipboard?', opts: ['Clipboard API', 'Storage API', 'History API', 'URL API'], answer: 0, explanation: 'The Clipboard API (navigator.clipboard) provides read/write access to the system clipboard asynchronously.' },
    { q: 'Geolocation.getCurrentPosition() is:', opts: ['Synchronous', 'Asynchronous (callback)', 'A Promise', 'Blocking'], answer: 1, explanation: 'Geolocation uses callbacks (success, error). It\'s async but predates Promises. Requires user permission.' },
    { q: 'IntersectionObserver detects:', opts: ['Click events', 'Element visibility in viewport', 'Network status', 'Screen size'], answer: 1, explanation: 'IntersectionObserver watches when elements enter/exit the viewport or an ancestor, useful for lazy loading and infinite scroll.' },
    { q: 'Which API enables background scripts for offline?', opts: ['Web Workers', 'Service Workers', 'WebSockets', 'IndexedDB'], answer: 1, explanation: 'Service Workers act as a network proxy, enabling offline support, caching, and push notifications.' }
  ],
  destructuring_and_spread: [
    { q: 'What does ...arr do when used in a function parameter?', opts: ['Spread', 'Rest (collects args)', 'Destructure', 'Clone'], answer: 1, explanation: 'In function parameters, ... is the rest operator — it collects remaining arguments into an array.' },
    { q: 'const {a: x} = {a: 1} — what is x?', opts: ['undefined', '{a:1}', '1', '"a"'], answer: 2, explanation: '{a: x} renames "a" to "x" during destructuring. x gets the value of a, which is 1.' },
    { q: 'What does [a, , b] = [1, 2, 3] assign to b?', opts: ['2', '3', 'undefined', 'Error'], answer: 1, explanation: 'The empty slot (,,) skips index 1. So a=1, index 1 is skipped, and b=3.' },
    { q: 'const [first, ...rest] = [1,2,3] — what is rest?', opts: ['[2,3]', '[1,2,3]', '3', '2'], answer: 0, explanation: 'Rest in array destructuring collects remaining elements. first=1, rest=[2,3].' },
    { q: 'What does this code print?', code: 'const user = { name: "Ana", age: 25 };\nconst clone = { ...user, age: 30 };\nconsole.log(user.age, clone.age);', opts: ['30, 30', '25, 30', '25, 25', 'Error'], answer: 1, explanation: 'Spread creates a shallow copy. The age: 30 after the spread overwrites clone.age. The original user is unchanged.' }
  ],
  json_and_dates: [
    { q: 'JSON.stringify() converts:', opts: ['String to object', 'Object to JSON string', 'JSON to array', 'Number to string'], answer: 1, explanation: 'JSON.stringify() serializes a JS value to a JSON string. JSON.parse() does the reverse.' },
    { q: 'new Date().getMonth() returns January as:', opts: ['1', '0', '"January"', '"Jan"'], answer: 1, explanation: 'Months are 0-indexed in JS Date: January=0, February=1, ... December=11. A common gotcha!' },
    { q: 'Which values does JSON.stringify() skip?', opts: ['Numbers', 'Strings', 'Functions and undefined', 'Arrays'], answer: 2, explanation: 'JSON.stringify() omits functions, undefined, and Symbol values. null and NaN are preserved.' },
    { q: 'Date.now() returns:', opts: ['A Date object', 'A formatted string', 'Milliseconds since epoch', 'Seconds since epoch'], answer: 2, explanation: 'Date.now() returns the number of milliseconds since January 1, 1970 (Unix epoch) as a number.' },
    { q: 'What does this code print?', code: 'const obj = { a: 1, b: undefined, c: function(){} };\nconsole.log(JSON.stringify(obj));', opts: ['{"a":1,"b":undefined,"c":"function(){}"}', '{"a":1}', '{"a":1,"b":null}', 'Error'], answer: 1, explanation: 'JSON.stringify() silently omits properties whose value is undefined or a function. Only {"a":1} remains.' }
  ],
  web_components: [
    { q: 'Custom element names must contain:', opts: ['Underscore', 'Hyphen', 'Number', 'Uppercase letter'], answer: 1, explanation: 'Custom elements require a hyphen (e.g., my-component) to avoid conflicts with current/future HTML elements.' },
    { q: 'Shadow DOM provides:', opts: ['Server rendering', 'Style encapsulation', 'Faster loading', 'Database access'], answer: 1, explanation: 'Shadow DOM creates an encapsulated DOM subtree with isolated styles that don\'t leak in or out.' },
    { q: 'Which lifecycle callback fires when element is added to DOM?', opts: ['constructor()', 'connectedCallback()', 'adoptedCallback()', 'attributeChangedCallback()'], answer: 1, explanation: 'connectedCallback() fires each time the element is inserted into the DOM. constructor() runs at creation time.' },
    { q: 'HTML templates render:', opts: ['Immediately on parse', 'Only when cloned and inserted', 'On page load', 'After DOMContentLoaded'], answer: 1, explanation: '<template> content is parsed but not rendered. You must clone it (cloneNode) and insert it into the DOM.' }
  ],
  testing_basics: [
    { q: 'In TDD, what do you write first?', opts: ['Implementation', 'Documentation', 'Failing test', 'Database schema'], answer: 2, explanation: 'Test-Driven Development: write a failing test first, then implement just enough code to pass it, then refactor.' },
    { q: 'AAA pattern stands for:', opts: ['Act-Assert-Arrange', 'Arrange-Act-Assert', 'Assert-Act-Arrange', 'Arrange-Assert-Act'], answer: 1, explanation: 'Arrange (setup), Act (execute), Assert (verify). This pattern keeps tests organized and readable.' },
    { q: 'A "mock" is:', opts: ['A real database', 'A fake implementation for testing', 'A test runner', 'A code formatter'], answer: 1, explanation: 'Mocks simulate dependencies (APIs, databases) so you can test units in isolation without side effects.' },
    { q: 'What does code coverage measure?', opts: ['Performance', 'How much code is executed by tests', 'Number of tests', 'File size'], answer: 1, explanation: 'Code coverage reports the percentage of lines, branches, and functions exercised by your test suite.' }
  ],
  logic_gates: [
    { q: 'What does the XOR gate return?', opts: ['true if both true', 'true if inputs differ', 'true if both false', 'always true'], answer: 1, explanation: 'XOR (exclusive OR) returns true only when inputs are different. In JS: a ^ b.' },
    { q: 'What is 5 & 3 in JavaScript?', opts: ['7', '1', '8', '15'], answer: 1, explanation: '5 is 101, 3 is 011 in binary. AND (101 & 011) = 001 = 1.' },
    { q: 'Which gate is called "universal" (can build all others)?', opts: ['AND', 'OR', 'NAND', 'XOR'], answer: 2, explanation: 'NAND (and NOR) are universal gates — any other gate can be constructed using only NAND gates.' },
    { q: 'What does this code print?', code: 'console.log(5 | 3);\nconsole.log(5 ^ 3);\nconsole.log(~5);', opts: ['7, 6, -6', '1, 6, -5', '7, 6, -5', '8, 6, -6'], answer: 0, explanation: '5|3: 101|011=111=7. 5^3: 101^011=110=6. ~5: bitwise NOT flips all bits, result is -(5+1)=-6.' }
  ],
  type_coercion: [
    { q: 'What does Number("") return?', opts: ['NaN', 'undefined', '0', 'null'], answer: 2, explanation: 'An empty string converts to 0. Whitespace-only strings also become 0. Only non-numeric strings yield NaN.' },
    { q: 'What does [] == false evaluate to?', opts: ['false', 'true', 'TypeError', 'undefined'], answer: 1, hint: 'Both sides coerce to numbers. What does [] become?', explanation: '[] coerces to "" (toString), then "" coerces to 0. false coerces to 0. So 0 == 0 is true.' },
    { q: 'What does 1 + 2 + "3" return?', opts: ['"123"', '"33"', '6', 'NaN'], answer: 1, explanation: 'Left to right: 1+2=3 (number+number), then 3+"3"="33" (number+string concatenates). Order matters!' },
    { q: 'Which is the ONLY safe use of == instead of ===?', opts: ['Comparing numbers', 'Checking null or undefined', 'Comparing arrays', 'Checking NaN'], answer: 1, explanation: 'value == null catches both null and undefined in one check. This is the only universally accepted == pattern.' },
    { q: 'What does this code print?', code: 'console.log(Number(null));\nconsole.log(Number(undefined));\nconsole.log(Number(false));', opts: ['0, NaN, 0', 'NaN, NaN, 0', '0, 0, 0', 'null, NaN, 0'], answer: 0, explanation: 'null → 0. undefined → NaN (it has no numeric equivalent). false → 0 (boolean coercion rule).' }
  ],
  this_keyword: [
    { q: 'What determines the value of "this" in a regular function?', opts: ['Where the function is defined', 'Where the function is called', 'The function name', 'The file it is in'], answer: 1, hint: 'JavaScript is call-time binding, not definition-time.', explanation: '"this" is determined at call time, not definition time. The call site (how/where it is invoked) sets "this".' },
    { q: 'Arrow functions bind "this" to:', opts: ['The global object', 'The nearest object', 'Their lexical enclosing scope', 'undefined always'], answer: 2, explanation: 'Arrow functions do not have their own "this". They inherit it from the enclosing scope where they were defined.' },
    { q: 'What does .bind() return?', opts: ['The result of calling the function', 'A new function with "this" permanently set', 'A Promise', 'The original function unchanged'], answer: 1, explanation: '.bind(ctx) returns a new function with "this" locked to ctx. It does not call the function immediately (unlike .call/.apply).' },
    { q: 'In which priority order is "this" determined?', opts: ['Default, method, explicit, new', 'new, explicit, method, default', 'Explicit, new, method, default', 'Method, new, explicit, default'], answer: 1, explanation: 'Priority: new binding > explicit (.call/.apply/.bind) > method call (obj.fn()) > default (global/undefined).' },
    { q: 'What does this code print?', code: 'const obj = {\n  name: "obj",\n  greet: function() { return this.name; }\n};\nconst fn = obj.greet;\nconsole.log(fn());', opts: ['"obj"', 'undefined', 'Error', '"window"'], answer: 1, explanation: 'Detaching a method loses its "this" binding. fn() is a standalone call — in strict mode this is undefined, so this.name is undefined.' }
  ],
  prototype_chain: [
    { q: 'Where does JS look for a property NOT found on an object?', opts: ['Global scope', 'The prototype chain', 'The constructor', 'Returns undefined immediately'], answer: 1, hint: 'Property lookup does not stop at the object itself.', explanation: 'JS traverses the prototype chain: obj → obj.__proto__ → obj.__proto__.__proto__ → null. Returns undefined only at the end.' },
    { q: 'Object.create(proto) creates an object whose prototype is:', opts: ['Object.prototype', 'null', 'proto', 'A new empty object'], answer: 2, explanation: 'Object.create(proto) returns a new object with proto as its [[Prototype]], giving you precise control over the chain.' },
    { q: 'hasOwnProperty() checks if a property is:', opts: ['Enumerable', 'Defined directly on the object (not inherited)', 'Writable', 'A string key'], answer: 1, explanation: 'hasOwnProperty() returns true only for properties defined directly on the object, not ones inherited from the prototype chain.' },
    { q: 'When you write "class Foo extends Bar", what does JS create?', opts: ['A copy of Bar', 'Foo.prototype.__proto__ = Bar.prototype', 'A new type system', 'Foo inherits Bar\'s constructor only'], answer: 1, explanation: 'classes are syntax sugar over prototypes. extends sets up Foo.prototype.__proto__ = Bar.prototype so the chain works.' },
    { q: 'What does this code print?', code: 'function Animal(name) {\n  this.name = name;\n}\nAnimal.prototype.speak = function() {\n  return this.name + " speaks";\n};\nconst a = new Animal("Cat");\nconsole.log(a.hasOwnProperty("speak"));\nconsole.log(a.speak());', opts: ['true, "Cat speaks"', 'false, "Cat speaks"', 'false, Error', 'true, Error'], answer: 1, explanation: 'speak is on Animal.prototype, not the instance. hasOwnProperty("speak") is false. But a.speak() works via the chain.' }
  ],
  property_descriptors: [
    { q: 'How many attributes does every JS property have?', opts: ['1', '2', '4', '6'], answer: 2, explanation: 'Every property has 4 descriptor attributes: value, writable, enumerable, and configurable.' },
    { q: 'What does Object.freeze() prevent?', opts: ['Adding properties only', 'Modifying properties only', 'Adding AND modifying AND deleting properties', 'Prototype changes only'], answer: 2, explanation: 'freeze() sets writable:false and configurable:false on all properties and prevents new property addition. It is shallow.' },
    { q: 'An accessor descriptor uses:', opts: ['value and writable', 'get and set', 'enumerable only', 'configurable only'], answer: 1, explanation: 'Accessor descriptors have get (getter function) and set (setter function) instead of a static value.' },
    { q: 'What happens when you try to change a configurable:false property descriptor?', opts: ['It silently does nothing', 'It throws TypeError in strict mode', 'It works normally', 'It deletes the property'], answer: 1, explanation: 'Once configurable is false, you cannot reconfigure the property. In strict mode this throws a TypeError.' },
    { q: 'What does this code print?', code: 'const obj = {};\nObject.defineProperty(obj, "x", {\n  value: 42,\n  writable: false,\n  enumerable: true\n});\nobj.x = 100;\nconsole.log(obj.x);', opts: ['100', '42', 'undefined', 'TypeError'], answer: 1, explanation: 'writable:false silently ignores assignment in non-strict mode (strict mode would throw). The value stays 42.' }
  ],
  functional_patterns: [
    { q: 'A pure function is one that:', opts: ['Uses no variables', 'Has no side effects and returns same output for same input', 'Is always async', 'Cannot be called twice'], answer: 1, hint: 'Think about predictability and external dependencies.', explanation: 'Pure functions are deterministic (same inputs → same output) and have no side effects (no mutations, no I/O).' },
    { q: 'What is function composition?', opts: ['Calling multiple functions at once', 'Applying functions so the output of one is the input of the next', 'A class method pattern', 'Currying'], answer: 1, explanation: 'compose(f, g)(x) = f(g(x)). The result of g is passed as input to f. Data flows right-to-left in compose, left-to-right in pipe.' },
    { q: 'What does a curried function do with extra arguments?', opts: ['Throws an error', 'Ignores them', 'Returns a new function waiting for the next argument', 'Converts them to an array'], answer: 2, explanation: 'Currying transforms f(a, b, c) into f(a)(b)(c). Each call returns a new function until all arguments are provided.' },
    { q: 'Memoization is useful when a function is:', opts: ['Simple and fast', 'Called once', 'Pure and called repeatedly with the same args', 'Async'], answer: 2, explanation: 'Memoization caches return values by input. It only helps for pure functions called multiple times with identical arguments.' },
    { q: 'What does this code print?', code: 'function once(fn) {\n  let called = false, result;\n  return function(...args) {\n    if (!called) { called = true; result = fn(...args); }\n    return result;\n  };\n}\nconst init = once((x) => x * 2);\nconsole.log(init(5));\nconsole.log(init(10));', opts: ['10, 20', '10, 10', '10, undefined', '5, 10'], answer: 1, explanation: 'once() only executes fn on the first call, caching the result. init(5)=10, then init(10) returns the cached 10.' }
  ]
};
